# Site settings
title               : تذكرتك
description         : طريقة جديدة لدفع تذاكر وسائل المواصلات عن طريق الهواتف الذكية
video_id            : b3RApFvBH2Q
long_description    : >-
                      يهدف تطبيق تذكرتك إلي المساهمة فى التحول الرقمي طبقاً
                      لرؤية مصر 2030 عن طريق تسهيل عملية الدفع على
                      المواطن في وسائل الموصلات والقضاء علي مشكلة الفكة
                      وتسهيل عملية التحصيل على الكمسرى.
                      كما إنه يحرص علي تزويد الهيئات المختصة ببيانات وإحصائيات
                      حول المعاملات اليومية وعدد الركاب على مدار السنة التي ستساهم
                      في معرفة عدد الركاب فى كل  خط سير والذى سيساعد على سبيل المثال
                      فى تزويد الحافلات لخطوط السير التى تعانى من نقص في عدد الحافلات.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - debug.log
  - firebase.json
