# Site settings
title               : تذكرتك
description         : طريقة جديدة لدفع تذاكر وسائل المواصلات عن طريق الهواتف الذكية
url                 : https://tazkrtak.web.app
video_id            : b3RApFvBH2Q

# Build settings
markdown            : kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - debug.log
  - firebase.json
